export type Status = 'operando' | 'advertencia' | 'alarma';

export interface EqDef {
  id:          string;
  label:       string;
  status:      Status;
  params:      [string, string][];
  description?: string;  // descripción general del equipo para el modal
  vb?:         string;   // viewBox crop "x y w h" para zoom en modal
  chartParam?: number;   // índice en params[] a graficar (default 0)
}

export const SC: Record<Status, string> = { operando: '#3fb950', advertencia: '#d29922', alarma: '#f85149' };
export const SB: Record<Status, string> = { operando: '#0d2d1a', advertencia: '#2d1f08', alarma: '#2d0a0a' };
export const SL: Record<Status, string> = { operando: '● EN OPERACIÓN', advertencia: '▲ ADVERTENCIA', alarma: '✖ ALARMA' };

export const EQ: Record<string, EqDef> = {
  /* FASE PRELIMINAR */
  rotativa:    { id:'rot',     label:'Descarga Rotativa',           status:'operando',
    description:'Punto de entrada del agua residual industrial proveniente del proceso de rotativa textil. Recibe el efluente crudo y lo conduce al tanque de recepción para iniciar el tratamiento. Monitorea caudal continuo, sólidos suspendidos totales (SST) y pH en tiempo real.',
    params:[['Caudal','5.2 m³/h'],['SST','640 mg/L'],['pH','7.9']],
    vb:'0 82 155 52', chartParam:0 },
  funza:       { id:'funza',   label:'Descarga Ext. Funza',         status:'advertencia',
    description:'Descarga externa procedente de la planta de Funza. Incorpora efluentes con alta carga orgánica (DQO elevada) y colorantes textiles. Requiere vigilancia especial por variabilidad en composición y concentración de contaminantes.',
    params:[['Caudal','6.0 m³/h'],['DQO','1800 mg/L'],['Color','alto']],
    vb:'0 106 160 52', chartParam:0 },
  tintoreria:  { id:'tintor',  label:'Descarga Tintorería',         status:'operando',
    description:'Efluente proveniente del proceso de tintura de telas. Presenta alta temperatura, pH alcalino y concentración elevada de colorantes reactivos y dispersos. Es uno de los flujos con mayor carga de contaminantes del sistema.',
    params:[['Caudal','12.4 m³/h'],['pH','9.8'],['Temp.','42 °C']],
    vb:'0 168 155 52', chartParam:0 },
  lavanderia:  { id:'lavand',  label:'Descarga Lavandería',         status:'operando',
    description:'Efluente del proceso de lavado de prendas. Contiene detergentes, lint textil, temperaturas moderadas y alta turbidez. Se canaliza hacia los tanques de recepción para pre-acondicionamiento antes del tratamiento primario.',
    params:[['Caudal','8.6 m³/h'],['Turb.','380 NTU'],['Temp.','38 °C']],
    vb:'0 188 155 52', chartParam:0 },
  tk2m3:       { id:'tk2m3',   label:'TK Recepción 2 m³',          status:'operando',
    description:'Tanque pequeño de recepción y mezcla para los efluentes de la Rotativa y la Descarga Externa Funza. Actúa como buffer de corto plazo para homogenizar caudales variables antes de pasar al pulmón principal de 60 m³.',
    params:[['Fuentes','Rotativa + Funza'],['Caudal E.','11 m³/h'],['Vol.','2 m³']],
    vb:'80 88 100 80', chartParam:1 },
  tk30m3:      { id:'tk30m3',  label:'TK Recepción 30 m³',         status:'operando',
    description:'Tanque de recepción de 30 m³ para los efluentes de Tintorería y Lavandería. Permite absorber variaciones de caudal y concentración, garantizando un flujo más estable y controlado hacia las etapas de cribado primario.',
    params:[['Fuentes','Tintorería + Lavand.'],['Caudal E.','25 m³/h'],['Vol.','30 m³']],
    vb:'75 172 105 95', chartParam:1 },
  tk15m3:      { id:'tk15m3',  label:'TK Buffer Lav. Remota 15 m³',status:'operando',
    description:'Tanque buffer de 15 m³ para el ramal remoto de Lavandería. Almacena temporalmente el efluente de una línea auxiliar de lavado, nivelando caudales intermitentes y protegiéndolos contra sobrecargas hidráulicas al sistema principal.',
    params:[['Fuente','Lavandería (ramal E)'],['Caudal E.','3.8 m³/h'],['Vol.','15 m³']],
    vb:'76 238 106 78', chartParam:1 },
  tk60m3:      { id:'tk60m3',  label:'TK Pulmón 60 m³',            status:'operando',
    description:'Tanque pulmón de 60 m³ que centraliza todos los afluentes preliminares. Regula las variaciones de caudal y concentración entre las descargas industriales discontinuas y el proceso de tratamiento continuo aguas abajo. Fundamental para la estabilidad operativa de la planta.',
    params:[['Nivel','72 %'],['Entrada G+H','≈ 40 m³/h'],['T. retención','1.5 h']],
    vb:'152 132 135 158', chartParam:0 },
  /* FASE PRIMARIA */
  cribRot:     { id:'cribRot', label:'Criba Rotativa',              status:'operando',
    description:'Equipo de tamizado rotativo con malla de 2 mm que retiene sólidos gruesos y fibras textiles del efluente crudo. El tambor giratorio (4 rpm) conduce los sólidos capturados hacia la tolva de descarga mientras el líquido pasa al interior para continuar el proceso.',
    params:[['Apertura','2 mm'],['Velocidad','4 rpm'],['Captura','35 kg/d']],
    vb:'262 105 180 170', chartParam:2 },
  vibrat1:     { id:'vib1',    label:'Criba Vibratoria 1 (M1)',     status:'operando',
    description:'Primera criba vibratoria de alta frecuencia con apertura de 0.5 mm. Separa partículas finas y fibras textiles sub-milimétrica mediante vibración mecánica. Opera en la primera etapa de cribado fino después de la criba rotativa, retirando material que podría dañar equipos aguas abajo.',
    params:[['Apertura','0.5 mm'],['Frecuencia','50 Hz'],['Potencia','2.2 kW']],
    vb:'370 72 175 168', chartParam:1 },
  vibrat2:     { id:'vib2',    label:'Criba Vibratoria 2 (M2)',     status:'operando',
    description:'Segunda criba vibratoria con apertura de 0.25 mm, la más fina del sistema de cribado. Realiza la separación sólido-líquido de último nivel antes del tanque pulmón. Trabaja en paralelo con M1 para garantizar continuidad operativa si una requiere mantenimiento.',
    params:[['Apertura','0.25 mm'],['Frecuencia','50 Hz'],['Potencia','2.2 kW']],
    vb:'370 164 175 168', chartParam:1 },
  tkPulmon:    { id:'tkPulm',  label:'TK Pulmón',                   status:'operando',
    description:'Tanque pulmón receptor del efluente ya cribado proveniente de ambas cribas vibratorias. Distribuye el flujo hacia la Torre de Enfriamiento (vía O) y el Cárcamo (vía R), regulando presiones y caudales para un funcionamiento estable de la fase primaria.',
    params:[['Nivel','65 %'],['Entradas','N1+N2 cribas'],['Salidas','O → Torre, R → Cárcamo']],
    vb:'508 140 148 175', chartParam:0 },
  torre:       { id:'torre',   label:'Torre de Enfriamiento',       status:'operando',
    description:'Torre de enfriamiento por evaporación que reduce la temperatura del efluente de 44 °C a ~28 °C. El proceso de evaporación parcial también elimina compuestos volátiles y vapores de tintorería. Imprescindible para proteger membranas y equipos biológicos de temperaturas elevadas.',
    params:[['T entrada','44 °C'],['T salida','28 °C'],['P','Pérd. vapor']],
    vb:'622 82 132 168', chartParam:0 },
  carcamo:     { id:'carc',    label:'Cárcamo',                     status:'operando',
    description:'Pozo de colecta y bombeo que centraliza el efluente proveniente del TK Pulmón y la Torre de Enfriamiento. Aloja las bombas de alimentación hacia la Fase Secundaria (AK1). Actúa como punto de control hidráulico entre la fase primaria y la secundaria.',
    params:[['Función','Colecta efluente'],['AK1','→ Fase Secundaria'],['Rebose','→ vertimiento']],
    vb:'626 202 120 132', chartParam:0 },
  homogen:     { id:'homog',   label:'TK Homogeneizador 800 m³',   status:'operando',
    description:'Tanque de homogeneización de gran volumen (800 m³) que mezcla los efluentes con ozono (O₃), coagulantes y lixiviados para ecualizar pH, concentración y temperatura. El agitador mecánico garantiza una mezcla homogénea antes del tratamiento fisicoquímico en el Equipo GEM.',
    params:[['Volumen','≈ 800 m³'],['pH ajust.','7.2'],['Entradas','Q + Ozono + Lixiviado']],
    vb:'722 128 168 198', chartParam:1 },
  eqGem:       { id:'gem',     label:'Equipo GEM',                  status:'operando',
    description:'Reactor fisicoquímico GEM (Gestión de Efluentes Mixtos) con dosificación múltiple: ácido, decolorante, coagulante, floculante catiónico y aniónico. Genera precipitados y flóculos que concentran colorantes, metales y SST para su posterior separación en el Swingmill.',
    params:[['Tipo','Reactor fisicoquímico'],['Reactivos','5 dosificaciones'],['Salida','U → Swingmill']],
    vb:'842 76 155 235', chartParam:0 },
  swingmill:   { id:'swing',   label:'Swingmill',                   status:'operando',
    description:'Espesador centrífugo que deshidrata y concentra los lodos fisicoquímicos provenientes del Equipo GEM. Separa la fracción sólida (lodo deshidratado para disposición final) del efluente clarificado que continúa hacia la Fase Secundaria. Reduce significativamente el volumen de lodos a gestionar.',
    params:[['Función','Espesado de lodos'],['Salida W','Lodo deshidratado'],['Caudal','5 m³/h']],
    vb:'955 170 145 145', chartParam:2 },
  /* FASE SECUNDARIA */
  tkPermeado:  { id:'tkPerm',  label:'TK Permeado',                 status:'operando',
    description:'Tanque receptor del efluente tratado proveniente de la Fase Primaria (vía AK1 desde el Cárcamo). Almacena temporalmente el agua pre-tratada y la distribuye de manera controlada hacia los biorreactores de membrana (MBR), asegurando condiciones hidráulicas estables.',
    params:[['Nivel','68 %'],['Entrada','AK1 desde Cárcamo'],['Rebose','AK1 → desborde']],
    vb:'1052 128 148 168', chartParam:0 },
  mbrT:        { id:'mbrT',    label:'MBR T (Superior)',            status:'operando',
    description:'Biorreactor de Membrana (MBR) superior con módulos de ultrafiltración sumergidos. Las membranas de fibra hueca retienen bacterias, sólidos y macromoléculas mientras producen un permeado de alta calidad. Combina la biodegradación aerobia con la separación por membrana en un solo reactor.',
    params:[['Flux','18 L/m²/h'],['TMP','-0.22 bar'],['Estado','en servicio']],
    vb:'1252 92 158 152', chartParam:0 },
  mbrK:        { id:'mbrK',    label:'MBR K (Inferior)',            status:'advertencia',
    description:'Biorreactor de Membrana (MBR) inferior, actualmente con aviso de CIP (Limpieza en Sitio) próximo. La presión transmembrana (TMP) elevada indica colmatación incipiente de las membranas. Requiere programar la limpieza química para restaurar el flujo nominal.',
    params:[['Flux','15 L/m²/h'],['TMP','-0.38 bar'],['CIP','próximo']],
    vb:'1252 215 158 152', chartParam:0 },
  mbbr:        { id:'mbbr',    label:'Reactor MBBR',                status:'operando',
    description:'Reactor de Lecho Móvil de Biopelícula (MBBR) con portadores plásticos al 65% de llenado. La biomasa adherida a los carriers realiza nitrificación y degradación de materia orgánica. Los difusores de fondo suministran oxígeno para mantener las condiciones aerobias necesarias.',
    params:[['Llenado','65 %'],['MLSS','4 800 mg/L'],['OD','2.4 mg/L']],
    vb:'1438 145 205 182', chartParam:2 },
  anoxic:      { id:'anox',    label:'Reactor Anóxico',             status:'operando',
    description:'Reactor anóxico sin aireación donde se produce la desnitrificación biológica: las bacterias heterotróficas convierten los nitratos (NO₃⁻) en nitrógeno gaseoso (N₂), reduciendo la carga de nitrógeno del efluente. Opera con OD < 0.2 mg/L y tiempo de retención de 4 horas.',
    params:[['OD','< 0.2 mg/L'],['NO₃⁻','8.4 mg/L'],['T. retención','4 h']],
    vb:'1648 145 195 178', chartParam:1 },
  /* FASE VERTIMIENTO */
  tkVert:   { id:'tkVert',   label:'TK Permeado Vertimiento', status:'operando',
    description:'Tanque de almacenamiento del efluente tratado destinado a vertimiento al cuerpo hídrico receptor. Almacena el agua que ha cumplido los estándares de calidad para descarga regulada. Actúa como buffer final antes de los filtros de pulido para la descarga legal al ambiente.',
    params:[['Función','Almacenamiento efluente tratado'],['Vol.','10 m³'],['DBO salida','< 5 mg/L']],
    vb:'1408 415 245 158', chartParam:1 },
  filtVert: { id:'filtVert', label:'Filtro Carbón Activado',  status:'operando',
    description:'Filtro de carbón activado granular (GAC) para pulido final del efluente de vertimiento. Adsorbe colorantes residuales, micropoluentes emergentes y compuestos orgánicos refractarios no eliminados en etapas anteriores. Garantiza que el agua descargada cumpla la normativa ambiental vigente.',
    params:[['Medio','Carbón granular GAC'],['Carga hidráulica','4 m/h'],['Turb. salida','< 1 NTU']],
    vb:'1418 522 156 168', chartParam:1 },
  /* FASE TERCIARIA */
  filtro5:     { id:'filt5',   label:'Filtros Cartucho 5 µm',      status:'operando',
    description:'Filtros de cartucho de 5 micras que actúan como etapa de pre-filtración antes de las membranas de ósmosis inversa. Retienen partículas finas, coloides y sólidos suspendidos que podrían colmatar prematuramente los elementos de RO, extendiendo significativamente su vida útil.',
    params:[['ΔP','0.22 bar'],['Flujo','42 m³/h'],['Reemplazo','en 12 d']],
    vb:'852 352 145 148', chartParam:1 },
  ro1e1:       { id:'ro1e1',   label:'Ósmosis Inversa RO1 – E1',   status:'operando',
    description:'Primer elemento de la primera etapa de Ósmosis Inversa RO1. Las membranas semipermeable rechazan sales disueltas, colorantes y contaminantes iónicos con una eficiencia del 98.5%, produciendo agua de alta pureza (TDS 18 mg/L) para reutilización en procesos textiles.',
    params:[['Recuperación','58 %'],['TDS perm.','18 mg/L'],['Sales rej.','98.5 %']],
    vb:'645 368 205 158', chartParam:0 },
  ro1e2:       { id:'ro1e2',   label:'Ósmosis Inversa RO1 – E2',   status:'operando',
    description:'Segundo elemento de RO1 que concentra el rechazo del E1 para maximizar la recuperación total del sistema. Produce un permeado de muy alta calidad (TDS 12 mg/L) que se envía directamente al TK de Recirculación para su reúso en producción textil.',
    params:[['Recuperación','62 %'],['TDS perm.','12 mg/L'],['Permeado AI','→ TK Recir.']],
    vb:'480 368 205 158', chartParam:0 },
  ro2:         { id:'ro2',     label:'Ósmosis Inversa RO2',         status:'alarma',
    description:'Segunda etapa de Ósmosis Inversa que trata el rechazo concentrado de RO1. Actualmente en alarma por fouling detectable en las membranas. Requiere limpieza CIP programada urgente para restaurar permeabilidad. En condiciones normales produce agua de alta recuperación del rechazo salino.',
    params:[['TMP','0.65 bar'],['Fouling','detectable'],['CIP','programado']],
    vb:'648 482 205 180', chartParam:0 },
  filtrosII:   { id:'filtII',  label:'Filtros Intercambio Iónico', status:'operando',
    description:'Columnas de resinas de intercambio iónico que eliminan iones divalentes (Ca²⁺, Mg²⁺, SO₄²⁻) y metales pesados del efluente secundario tratado. Producen agua ablandada (AE) lista para alimentar la primera etapa de Ósmosis Inversa, protegiéndola del encostramiento calcáreo.',
    params:[['Entrada','AE desde Sec.'],['Resinas','en servicio'],['Salida AF','→ RO1']],
    vb:'988 405 218 118', chartParam:0 },
  tkRecir:     { id:'tkRecir', label:'TK Recirculación',           status:'operando',
    description:'Tanque de almacenamiento y distribución del agua de alta calidad recuperada del proceso de ósmosis inversa (RO1 E2 y otras corrientes AQ/AR/AS). Constituye el punto de entrega de agua reciclada hacia Producción, cerrando el ciclo de reúso hídrico de la planta textil.',
    params:[['Vol.','30 m³'],['Fuentes','RO1 E2 + AQ/AR/AS'],['Salida','→ Producción']],
    vb:'115 498 212 158', chartParam:0 },
  tkRechazo:   { id:'tkRech',  label:'TK Rechazo RO1',            status:'advertencia',
    description:'Tanque receptor del rechazo concentrado de la primera etapa de RO1 (E2). Almacena temporalmente el corriente de alta salinidad para su posterior tratamiento en RO2 o derivación a la Caja de Vertimiento. Actualmente en advertencia por nivel elevado de sólidos en el rechazo.',
    params:[['Entrada AJ','Rechazo RO1 E2'],['AK','→ Filtro → RO2'],['Desborde','→ Caja Vert.']],
    vb:'452 524 162 138', chartParam:0 },
  tkRechazoRO2:{ id:'tkRech2', label:'TK Rechazo RO2',            status:'advertencia',
    description:'Tanque de almacenamiento del rechazo concentrado final de RO2. Este flujo tiene la mayor concentración de sales y contaminantes del sistema. Se dirige a la Caja de Vertimiento para su descarga controlada o hacia tratamiento adicional. En advertencia por elevado contenido de sólidos.',
    params:[['Entrada','Rechazo RO2'],['Salida','→ Caja Vertimiento'],['Caudal','6 m³/h']],
    vb:'775 524 162 138', chartParam:2 },
  cajaVert:    { id:'cajaV',   label:'Caja Vertimiento Terc.',     status:'operando',
    description:'Estructura de colecta y derivación del efluente terciario hacia la Fase de Vertimiento. Recibe los excesos y rechazos de la Fase Terciaria (rechazos de RO, desbordamientos) y los canaliza hacia el sistema de tratamiento final antes de la descarga regulada al cuerpo receptor.',
    params:[['Destino','Fase Vertimiento'],['Pipe AT','→ VERT.'],['Caudal','8 m³/h']],
    vb:'985 524 162 138', chartParam:2 },
  produccion:  { id:'prod',    label:'Producción REÚSO',           status:'operando',
    description:'Punto de entrega final del agua recuperada y tratada hacia los procesos productivos textiles. El agua de reúso cumple los estándares de calidad para uso en tintorería, lavandería y otros procesos, generando un ahorro significativo en el consumo de agua potable y reduciendo el impacto ambiental.',
    params:[['Flujo','22 m³/h'],['Calidad','Textil ✓'],['Ahorro','$53k/mes']],
    vb:'0 342 178 178', chartParam:0 },
};
