export const CONTADORES = [
  // ─── Diarios principales ─────────────────────────────────────────────────
  { id: 'C-01', nombre: 'Contador Entrada Agua Potable Principal 6"',
    descripcion: 'Acueducto o carrotanques → Tanque de Recirculación',
    ubicacion: 'Entrada Principal',      tipo_agua: 'Entra T.Recirc',  factor_delta: 10  },
  { id: 'C-02', nombre: 'Contador Entrada Agua Potable Fría Lavandería (4")',
    descripcion: 'Tanque de Recirculación → Producción Lavandería',
    ubicacion: 'Lavandería',             tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-03', nombre: 'Contador Entrada Agua Potable LAB Lavandería',
    descripcion: 'Tanque de Recirculación → LAB Lavandería',
    ubicacion: 'LAB Lavandería',         tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-08', nombre: 'Abridora 1',
    descripcion: 'Tanque de Recirculación → Tintorería (Abridoras)',
    ubicacion: 'Proceso',                tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-09', nombre: 'Abridora 2',
    descripcion: 'Tanque de Recirculación → Tintorería (Abridoras)',
    ubicacion: 'Proceso',                tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-10', nombre: 'Tanque de Recirculación 2"',
    descripcion: 'Acueducto → Tanque de Recirculación',
    ubicacion: 'Tanque de Recirculación', tipo_agua: 'Entra T.Recirc'                    },
  { id: 'C-11', nombre: 'PTAR',
    descripcion: 'Tanque de Recirculación → Abastecimiento agua potable PTAR',
    ubicacion: 'Entrada PTAR',           tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-12', nombre: 'Entrada RO #1',
    descripcion: 'Agua tratada fase 2 (PTAR) → entrada RO fase 3',
    ubicacion: 'Módulo RO #1',           tipo_agua: 'PTAR → RO',       unidad: 'm³/h',  factor_delta: 0.001 },
  { id: 'C-13', nombre: 'Salida RO #1',
    descripcion: 'Permeado RO alimenta Tanque de Recirculación',
    ubicacion: 'Módulo RO #1',           tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-16', nombre: 'Entrada Agua Potable Rotativa 3"',
    descripcion: 'Tanque de Recirculación → Producción Rotativa',
    ubicacion: 'Rotativa',               tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-17', nombre: 'Medidor VERDE DIGITAL Retorno',
    descripcion: 'Retorno Tintorería (intercambio calor) → Tanque de Recirculación',
    ubicacion: 'Retorno',                tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-36', nombre: 'GEM PRUEBA',
    descripcion: 'Agua residual → Tratamiento',
    ubicacion: 'GEM',                    tipo_agua: '→ Tratamiento'                      },
  { id: 'C-19', nombre: 'Envío a TH',
    descripcion: 'Agua residual → Tratamiento (Torre de Homogenización)',
    ubicacion: 'Torre Enfriamiento',     tipo_agua: '→ Tratamiento'                      },
  { id: 'C-20', nombre: 'MBR 1',
    descripcion: 'Tratamiento fase 2 — Reactor MBR Kubota',
    ubicacion: 'Reactor MBR 1',          tipo_agua: 'Salida Tratada'                     },
  { id: 'C-21', nombre: 'MBR 2',
    descripcion: 'Tratamiento fase 2 — Reactor MBR Toray',
    ubicacion: 'Reactor MBR 2',          tipo_agua: 'Salida Tratada'                     },
  { id: 'C-22', nombre: 'Medidor de Ingreso UF PTAP',
    descripcion: 'Ingreso PTAP',
    ubicacion: 'UF PTAP',                tipo_agua: 'Fuente Pozo'                        },
  { id: 'C-23', nombre: 'Medidor Salida UF PTAP',
    descripcion: 'Salida PTAP/UF → Tanque de Recirculación',
    ubicacion: 'UF PTAP',                tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-26', nombre: 'Entrada Agua Potable Cuarto Químicos',
    descripcion: 'Acueducto Cuarto Químicos → Tanque de Recirculación',
    ubicacion: 'Cuarto Químicos',        tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-27', nombre: 'Agua Caliente Tintorería (Digital)',
    descripcion: 'Tanque de agua caliente (Calderas) → Producción Tintorería',
    ubicacion: 'Tintorería',             tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-28', nombre: 'Medidor Prueba Agua Caliente',
    descripcion: 'Misma ubicación que Agua Caliente Tintorería (Digital)',
    ubicacion: 'Prueba Caldera',         tipo_agua: 'Sale T.Recirc'                      },

  // ─── Opcionales ──────────────────────────────────────────────────────────
  { id: 'C-04', nombre: 'Entrada Agua Medidor Rojo Tintorería (4")',
    descripcion: 'Tintorería — medidor rojo',
    ubicacion: 'Tintorería',             tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-05', nombre: 'Entrada Agua Potable Fría Tintorería (4")',
    descripcion: 'Agua fría Tintorería',
    ubicacion: 'Tintorería',             tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-06', nombre: 'Entrada Agua Medidor Rojo Lavandería (4")',
    descripcion: 'Lavandería — medidor rojo',
    ubicacion: 'Lavandería',             tipo_agua: 'Sale T.Recirc'                      },
  { id: 'C-07', nombre: 'Rama',
    descripcion: 'Distribución general',
    ubicacion: 'Distribución',           tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-14', nombre: 'Entrada RO #2',
    descripcion: 'Agua tratada fase 2 (PTAR) → entrada RO #2 fase 3',
    ubicacion: 'Módulo RO #2',           tipo_agua: 'PTAR → RO'                         },
  { id: 'C-15', nombre: 'Salida RO #2',
    descripcion: 'Permeado RO #2 → Tanque de Recirculación',
    ubicacion: 'Módulo RO #2',           tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-18', nombre: 'Contador Entrada Agua Potable Tintorería 6"',
    descripcion: 'Entrada agua potable Tintorería',
    ubicacion: 'Tintorería',             tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-24', nombre: 'Entrada Agua Potable PTAR 2 (½") — Tanque Recirculación',
    descripcion: 'Acueducto PTAR 2 → Tanque de Recirculación',
    ubicacion: 'PTAR 2 — Acueducto',    tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-25', nombre: 'Entrada Agua Potable Puerta 4 — Acueducto',
    descripcion: 'Acueducto Puerta 4',
    ubicacion: 'Puerta 4',               tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-29', nombre: 'Entrada Agua Potable Puerta 2 — Acueducto',
    descripcion: 'Acueducto Puerta 2',
    ubicacion: 'Puerta 2',               tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-30', nombre: 'Entrada Agua Potable Caldera — Acueducto',
    descripcion: 'Acueducto Caldera',
    ubicacion: 'Caldera',                tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-31', nombre: 'Entrada Agua Potable Puerta 5 — Acueducto',
    descripcion: 'Acueducto Puerta 5',
    ubicacion: 'Puerta 5',               tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-32', nombre: 'Entrada Agua Potable Puerta 6 — Acueducto',
    descripcion: 'Acueducto Puerta 6',
    ubicacion: 'Puerta 6',               tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-33', nombre: 'Entrada Agua Potable Puerta 7 — Acueducto',
    descripcion: 'Acueducto Puerta 7',
    ubicacion: 'Puerta 7',               tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-34', nombre: 'Entrada Agua Potable ½" Lavandería — Acueducto',
    descripcion: 'Acueducto Lavandería ½"',
    ubicacion: 'Lavandería — Acueducto', tipo_agua: 'Entra T.Recirc'                     },
  { id: 'C-35', nombre: 'Entrada Agua Potable Zona de Lodos ½" (Lava Ojos)',
    descripcion: 'Acueducto Zona de Lodos / Lava Ojos',
    ubicacion: 'Zona de Lodos',          tipo_agua: 'Entra T.Recirc'                     },
] as const;

export type ContadorId = typeof CONTADORES[number]['id'];

// Orden fijo de los 20 contadores principales (aparecen siempre en este orden)
export const DIARIOS_IDS: ContadorId[] = [
  'C-01', 'C-02', 'C-03', 'C-08', 'C-09', 'C-10', 'C-11', 'C-12', 'C-13',
  'C-16', 'C-17', 'C-36', 'C-19', 'C-20', 'C-21', 'C-22', 'C-23', 'C-26', 'C-27', 'C-28',
];

export const CONTADORES_MAP = Object.fromEntries(CONTADORES.map(c => [c.id, c])) as Record<ContadorId, typeof CONTADORES[number]>;
export const CONTADORES_DIARIOS    = DIARIOS_IDS.map(id => CONTADORES_MAP[id]);
export const CONTADORES_OPCIONALES = CONTADORES.filter(c => !DIARIOS_IDS.includes(c.id as ContadorId));

export const TIPO_AGUA_CLASS: Record<string, string> = {
  'Entra T.Recirc':  'badge-agua-potable',
  'Sale T.Recirc':   'badge-agua-industrial',
  '→ Tratamiento':   'badge-agua-residual',
  'Salida Tratada':  'badge-agua-tratada',
  'PTAR → RO':       'badge-agua-pretratamiento',
  'Fuente Pozo':     'badge-agua-ro',
  // legacy (por si algún registro antiguo referencia estos valores)
  Potable:           'badge-agua-potable',
  'Reúso':           'badge-agua-reuso',
  RO:                'badge-agua-ro',
  Rechazo:           'badge-agua-rechazo',
  Tratada:           'badge-agua-tratada',
  Industrial:        'badge-agua-industrial',
  Residual:          'badge-agua-residual',
  Pretratamiento:    'badge-agua-pretratamiento',
};
